# Generated by Django 4.2.16 on 2024-10-21 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import superuser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adminprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', superuser.models.RegistrationNumberField(max_length=10, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('address_distract', models.CharField(blank=True, max_length=255, null=True)),
                ('address_taluka', models.CharField(blank=True, max_length=255, null=True)),
                ('address_pin_code', models.IntegerField()),
                ('adhar_number', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='admin/photos')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='admin/photos')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
