# Generated by Django 5.1.1 on 2024-10-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_gatepass_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='gatepass_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
