# Generated by Django 5.1.1 on 2024-10-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_alter_gatepass_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatepass',
            old_name='date_in',
            new_name='time_in',
        ),
    ]
