# Generated by Django 5.1.3 on 2024-11-13 11:11

import userprofiles.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0008_rename_date_in_gatepass_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='gatepass_number',
            field=userprofiles.models.GatepassNumberField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
