# Generated by Django 5.1.3 on 2024-11-18 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_alter_gatepass_gatepass_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='time_out',
        ),
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('gatepass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.gatepass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
