# Generated by Django 5.1.3 on 2024-11-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0010_remove_gatepass_time_in_remove_gatepass_time_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
