# Generated by Django 5.1.3 on 2024-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0012_remove_entry_gatepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='gatepass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
