# Generated by Django 5.1.3 on 2024-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0013_entry_gatepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='activities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='alert',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='image_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='matching_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
