# Generated by Django 5.1.3 on 2024-12-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0016_entry_detected_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='matching_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
