# Generated by Django 5.1.3 on 2024-12-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0022_alter_flagelement_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagelement',
            name='real_t_match',
            field=models.FloatField(default=0),
        ),
    ]
