# Generated by Django 5.1.3 on 2024-12-21 08:05

import userprofiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0024_matchelement_remove_flagelement_real_t_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_distract',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_pin_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_taluka',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_adhar_verify',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=userprofiles.models.UserProfilePhotoPath(2)),
        ),
    ]
