# Generated by Django 4.2.16 on 2024-12-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0025_remove_userprofile_address_distract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='gatepass_number',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
